### ISSUE TITLE
approach0 service down

### ISSUE THREAD

**Issue by VincentTam** [approach0/ui-approach0#1]
![Screenshot from 2020-12-16 11-19-21](https://user-images.githubusercontent.com/5748535/102335716-8e4a3300-3f90-11eb-9533-9f433b82a549.png)

Browser: Opera 71.0.3770.198
OS: Ubuntu 20.04 LTS
Actual URL: https://approach0.xyz/search/?q=%24%5Csum_%7Bi%3D1%7D%5En%5Cfrac%7B1%7D%7Bi%5Cleft(i%2B1%5Cright)%7D%24&p=1

**Comment by w32zhong** [comment]
@VincentTam  Yep, Docker swarm network is not working for some reason, I am still working on it...  Thanks for the notice.

**Comment by w32zhong** [comment]
The site is up now, although the indices is incomplete, I will switch to a more complete index shortly.

**Comment by w32zhong** [comment]
Approach Zero service with a complete index has been restored just now.

**Comment by hbghlyj** [comment]
Oops! Seems like server is down again
